Refactored
pelpro/smart-home-2019 pull request #1
Opened 2019-03-06 22:06 UTC by pelpro

2019-03-08 12:46 UTC, iagoshkov requested changes
Переделайте в соответствии с замечаниями.
Уберите из git .class файлы, все что генерируется во время сборки проекта не должно жить в системе контроля версий, в ней храним только исходный код.

2019-03-08 12:46 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            LightHandler.handleLightEvent(smartHome, event);
Вы починили SRP перенеся функционал в отдельные классы, но не починили OCP.
Нужно сделать абстракцию (интерфейс) для всех handler-ов и в цикле работать уже с абстракцией.
Сделайте как мы на занятии разбирали - коллекцию handler-ов, а внутри цикла по событиям - еще один вложенный цикл по коллекции handler-ов.

2019-03-08 12:46 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/DoorHandler.java
> +    public static void handleDoorEvent(SmartHome smartHome, SensorEvent event) {
Нужно избавиться от statiс метода и поддерживать абстрактный интерфейс EventHandler.

2019-03-08 12:46 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/DoorHandler.java
> +                            hallDoorClosing(smartHome, room);
Проигрывание сценариев умного дома - это отдельная responsibility, как мы и обсуждали на занятии, нужно ее вынести в отдельный класс (отдельный eventhandler).
Иначе при добавлении новых сценариев нам придется каждый раз менять код этого класса и встраивать новые if-ы и циклы.

2019-03-08 12:46 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/GsonHomeReader.java
> +
Хотя бы в stdout напишите что-нибудь про ошибку )

2019-03-08 12:46 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/LightHandler.java
> +public class LightHandler{
Здесь аналогично DoorHandler - имплементируйте общий интерфейс и никаких статик методов.

2019-03-13 17:14 UTC, pelpro reviewed
new commit

2019-03-13 17:15 UTC, pelpro commented
закоммитил второе дз с исправленным первым

2019-03-17 12:24 UTC, iagoshkov requested changes
Исправьте в соответствии с замечаниями.
И вообще у вас и у ekalamina и еще у кого-то (не помню уже) - одинаковый код. Делайте пожалуйста домашние задания самостоятельно, а то будет у всех -1 жизнь, даже разбираться не будут кто у кого списал.

2019-03-17 12:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +        if (action.get_type_name().equals("light_type")) {
А если я хочу сделать action который должен обработать и двери и свет?
Какой type_name мне тогда возвращать?
Здесь нужно сделать по аналогии с EventHandler-ами.
Мы должны всегда вызывать action, а уже внутри action-а решать хотим мы этот типа объекта обрабатывать или нет.Исправьте в соотвествии с замечаниями.

2019-03-17 12:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void execute(Action action) {
Сам дом тоже надо передать в action

2019-03-17 12:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +        if (action.get_type_name().equals("light_type")) {
+ саму комнату тоже надо передать в action - мы хотим сделать внутренний итератор, который обходит ВСЕ объекты дома, а не только свет и двери

2019-03-17 12:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +public interface Action<T> {
Зачем у Action get_room_name()?
Вот я хочу сделать новый action который будет обрабатывать например вообще все объекты дома.
Мне какой room_name возвращать и зачем вообще возвращать его???

Избавьтесь от этого метода в интерфейсе.
И от get_type_name - я ниже написал что нужно сделать.

И не передавайте в launchAction room_name - в него могут попадать объекты вообще не из комнат, причем тут room_name вообще?
А если я сам дом хочу обработать и мне в object придет дом, то вместе с ним какой room_name придет?
Если вам внутри реализации Action нужен room_name - нужно придумать другой подход.

2019-03-17 12:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/TurnOffLight.java
> +        if (light_id.equals(object.getId()) || light_id.equals("hallclose")) {
Вы здесь SRP нарушаете, у вас в TurnOffLight пролезли детали сценария умного дома.
Вам этот класс придется менять по двум причинам - обновление модели дома и изменения сценария, если мы например при закрытии входной двери больше не захотим выключат свет во всем доме.
Это должно быть в разных классах.

2019-03-20 18:09 UTC, pelpro commented on src/main/java/ru/sbt/mipt/oop/TurnOffLight.java
> +        if (light_id.equals(object.getId()) || light_id.equals("hallclose")) {
Я правильно понимаю что вообще лучше избавиться от классов описывающих действия и реализовать их внутри соответствующих элементов?
P.S. в этих коммитах к проверке только alarm-package, decorator, alarmhandler

2019-03-23 10:38 UTC, iagoshkov requested changes
Исправьте замечания + не увидел тестов на Alarm

2019-03-23 10:38 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        Collection<EventHandler> EventsCollection = new ArrayList<>();
А alarm handler-ы где?

2019-03-23 10:38 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/TurnOffLight.java
> +        if (light_id.equals(object.getId()) || light_id.equals("hallclose")) {
необязательно избавляться от отдельных классов-действий, так тоже можно

2019-03-23 10:38 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmAlert.java
> +            setState(new AlarmDeactivate());
зовите setState у объекта alarm, а не сохраняйте в поле

2019-03-23 10:38 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +        setState(state.getState());
уберите setState из методов в alarm и зовите alarm.setState изнутри самих классов-состояний

2019-03-23 10:38 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
> +public class Alarm {
можно сделать чтобы Alarm implements AlarmState.

2019-04-09 19:00 UTC, iagoshkov requested changes
По пульту и командам пока незачет, см. комментарии

2019-04-09 19:00 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/remoteControl/RemoteController.java
> +        if (buttonCharCode >= 'A' && buttonCharCode <= 'D' || buttonCharCode >= '1' && buttonCharCode <= '4') {
А зачем здесь эта проверка?
А если мы захотим сделать пульт с другим набором кнопок, нам эти проверки менять нужно?

2019-04-09 19:00 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/remoteControl/RemoteController.java
> +        Buttons button = buttons.get(buttonCode);
А если нажали кнопку, для которой незарегистрирован обработчик?
Будет NullPointerException?

2019-04-09 19:00 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        GsonHomeReader reader = new GsonHomeReader("smart-home-1.js");
А где инициализация пульта, регистрация команд в нем?
Регистрация пульта в библиотеке?

2019-05-28 18:36 UTC, merged